### ISSUE TITLE
'check all' vs verifying what's actually downloaded

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#104]
I'm reading the FAQ and still unsure, but just want to clarify.

'Checking all' will download a list of videos, and then that compares it against that youtube link text archive that gets created for each channel, correct?

If that is the case, is there any way to verify the existence of the file? For example, if a video was downloaded, but then deleted off the system (could be malice, network error, hard drive error, etc), would tartube know the video file no longer exists?

**Comment by axcore** [comment]
> 'Checking all' will download a list of videos, and then that compares it against that youtube link text archive that gets created for each channel, correct?

As far as I know, the Check All and Download All operations are identical (except that in Check All, youtube-dl says "I would have downloaded this video", instead of downloading it.)

So both Check All and Download All will ignore videos in the archive file.

>If that is the case, is there any way to verify the existence of the file?

During the download operation, Tartube checks for itself whether the video file actually exists on your filesystem. It doesn't rely on youtube-dl's assurances that the file exists.

You can click **Operations > Refresh database**. This will look for videos which should exist, but no longer do. It will also look for videos which should not exist, but do (and will add them to the database).
