### ISSUE TITLE
Option to skip file?

### ISSUE THREAD

**Issue by kdliu86** [axcore/tartube#105]
Is there a way to check a box (either by marking it as "skipped" or "ignored") so it skips a certain video during "download channel"?  I am using this on a guitar lesson channel and the guy remade some of his lessons so there's duplicates (even triplicates) of the same lesson.

As I understand it, youtube-dl reads download-archive to skip; perhaps the checkbox could add/remove the link to the download-archive.

**Comment by axcore** [comment]
That feature doesn't exist yet, but it's a good idea.

**Comment by axcore** [comment]
Since yesterday's reply, I remembered thinking about a similar issue before.

The archive file contains each downloaded video's ID. I had not been able to find a reliable way to obtain a video's ID that works on all websites. Unless I can think of a way, then I don't know how the feature can be implemented.
