### ISSUE TITLE
Windows 10 64-bit installer issue

### ISSUE THREAD

**Issue by korgano** [axcore/tartube#12]
Got this error after uninstalling a Tartube installation that wouldn't activate. Can't use the manual method since https://msys2.org/ is unavailable, and turning off anti-virus and firewall software did nothing.

![tartube_error](https://user-images.githubusercontent.com/1180905/62424958-ac690900-b6a3-11e9-98f5-aade133892f4.jpg)

**Comment by axcore** [comment]
Hi korgano,

I haven't seen this error before, and I have no idea what might be causing it (or how to fix it).

**Comment by NormandoHall** [comment]
The same for me, Windows 7, 64 bit, marked as repmalware from Avast

![image](https://user-images.githubusercontent.com/2943127/71530560-096e9100-28c9-11ea-9d45-f7dd81d72db0.png)

**Comment by axcore** [comment]
Hi NormandoHall,

False positives are actually fairly common for anything packaged with NSIS (see [here](https://nsis.sourceforge.io/NSIS_False_Positives) for a taste).

I checked the Tartube 64-bit installer on the usual malware scan site, you can see the the result [here](https://virusscan.jotti.org/en-GB/filescanjob/hg6iajes9h). Avast and the other virus checkers don't see any problems, but because they are all updated daily, that doesn't mean that the Avast you have installed on your system will behave the same way.

I've submitted a false positive report to Avast. I don't know how long it might take them to act on it. In the meantime, these are your options:

1. Use an earlier version of Tartube, if Avast is happy with it. If Tartube has never been installed on your system, it's safe to use v1.3.0. Otherwise, use v1.2.008
2. Install Tartube manually. It's pretty simple, and the only .exe is the Msys2 one described at the top of this page.
3. Use [youtube-dl-gui](https://mrs0m30n3.github.io/youtube-dl-gui/). Tartube is a fork of youtube-dl-gui and has very similar capabilities.

**Comment by NormandoHall** [comment]
Thanks @axcore . I was disabled shields from Avast, installed, and enabled again.

Regards!

**Comment by axcore** [comment]
Apparently, "FileRepMalware" means that the virus checker hasn't seen this file very often, not that some malware has been detected. For example, see these threads on the Avast forum: [here](https://forum.avast.com/index.php?topic=209862.0) and [here](https://forum.avast.com/index.php?topic=124265.0).

**Comment by AkgunFatih** [comment]
i came here to say `Fuck Microsoft Windows`

**Comment by axcore** [comment]
@AkgunFatih I can't argue with that.
