### ISSUE TITLE
how to add shortcuts for Tartube from PyPI

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#120]
how to create shortcuts for Tartube from PyPI (without root privileges)

**Comment by axcore** [comment]
What kind of shortcuts do you mean? Do you mean, desktop shortcuts?

[This issue](https://github.com/axcore/tartube/issues/109) asks the same question. The answer is: I don't know how to create desktop shortcuts for PyPI installs. Lots of people claim it is possible, but no-one can show me some actual code.

**Comment by candrapersada** [comment]
yes desktop shortcuts for PyPI on Linux and desktop shortcuts for portable on MS Windows #85

**Comment by axcore** [comment]
For PyPI: I don't know how to do it

For MS Windows portable edition: you can easily create your own shortcut. The executable is `..\tartube\tartube_portable_64bit.bat`, so right-click that and select **Create shortcut**

**Comment by beew** [comment]
You can just create a .desktop file, make it executable and put it in ~/.local/share/applications. The executable line is just
```
EXEC=tartube 
```
This works because pip installs tartube in ~/.local/bin which is already in your PATH if you are using Ubuntu, if not either add it to your PATH by adding this line to .bashrc or .profile, logout and login again\

```
export PATH=$PATH:/home/username/.local/bin

```

or use the full path for tartube in the "EXEC="  line in your .desktop file (full path would be /home/username/.local/bin/tartube

You can choose any picture for the icon.

P.S If you use gnome in Ubuntu20.04 Nautilus is a bit of a pain to execute .desktop files in .local/share/applications. You may need to check with the forum if you have problems.

**Comment by axcore** [comment]
Thanks @beew, I had already tried a similar method, but it won't hurt to try it again.

**Comment by beew** [comment]
https://www.linuxuprising.com/2018/05/nautilus-will-no-longer-launch-binaries.html

> Nautilus (or Files), the Gnome file manager, received a Git update which removes its ability to launch binaries or programs in general. That means you won't be able to double click binaries, scripts, or desktop files to run them - this includes the ask dialog which lets you choose if the file should be launched or displayed.

This is the problem I mentioned. You may need to put the .desktop file in /usr/local/share/applications (requires root)
It works on other DE and/or file managers though. I am using Unity in Ubuntu20.04 with Nemo as the file manager and kubuntu 20.04on another machine,  I have no problem creating a desktop launcher
