### ISSUE TITLE
add 1.0.0 release on github

### ISSUE THREAD

**Issue by legrostdg** [axcore/tartube#13]
It would help Debian packaging to have a github release tarball. Is this something you could add?

**Comment by axcore** [comment]
Hi legrostdg,

The release tarball, on which everything is based, is this one:

https://sourceforge.net/projects/tartube/files/v1.0.0/tartube_v1.0.0.tar.gz/download

I can't see an option anywhere on my github page to add the same tarball, but I will do that, if you can show me where it is.

**Comment by legrostdg** [comment]
You can have a look to https://help.github.com/en/articles/creating-releases

**Comment by axcore** [comment]
Ok, it's done.

**Comment by legrostdg** [comment]
Thanks!
Concerning the .deb, I'm aiming for proper inclusion in Debian. In particular, it means that all the dependencies have to be packaged individually.

**Comment by axcore** [comment]
Then I will leave it in your capable hands. As far as I know, the only dependencies are python3, pip3 (so that youtube-dl can be updated), gtk3, pygobject and the python Requests library. 

The python3 moviepy module is optional. It's only used for getting the length of a downloaded video if the user chooses not to fetch the video metadata directly from the website. Include it or don't; I doubt anyone will notice.
