### ISSUE TITLE
add a build option to turn youtube-dl binary update off

### ISSUE THREAD

**Issue by legrostdg** [axcore/tartube#14]
We have to turn youtube-dl binary update off if we want tartube to enter Debian. One option is for the packager (probably me) to add a patch to remove this functionality, but keeping it up to date can be time consuming. It would be a lot easier to have a way to turn this off at build time (with an environment variable or command line option)

**Comment by axcore** [comment]
I could add a command line option like this:

> python3 tartube --no-update

Would that work for you?

**Comment by legrostdg** [comment]
Mmmh, I don't think so... Debian requires that no binary can be downloaded from the internet by a package: tartube has to use youtube-dl provided by the Debian package. This solution would allow the user to run `python3 tartube` and get updates. The best would be a flag that can be set at build time, something like "python3 setup.py build --no-updates"

**Comment by axcore** [comment]
According to various stuff on stackoverflow, it's not possible to use custom switches at the moment, because pip is broken. Therefore I have added an environment variable.

For the default version of Tartube, in which youtube-dl updates are enabled, you would use

python3 setup.py build 

For a modified version, in which youtube-dl updates are completely disabled, you would use

TARTUBE_NO_UPDATES=1 python3 setup.py build 

The changes are in v1.0.024. The menu option to update youtube-dl can no longer be clicked (and there are other safeguards to). Is that acceptable?

**Comment by legrostdg** [comment]
Great, thanks! Could you tag v1.0.024 (and make the release tarball on github)?

**Comment by axcore** [comment]
If you're sure that you're happy with this, I can release it as v1.1.0.

**Comment by legrostdg** [comment]
That's perfect.

**Comment by axcore** [comment]
I found a couple of bugs that must be fixed. v1.1.0 won't be ready for another day (or two).

**Comment by axcore** [comment]
Added in v1.1.0.
