### ISSUE TITLE
tidying up does nothing!

### ISSUE THREAD

**Issue by xal3xhx** [axcore/tartube#189]
I have a whole channel downloaded, around 300 videos. I have been trying to run the tidy channel feature but it appears to be doing nothing. Even if I select one thing (move thumbnails to folder). Any ideas and what other info should I provide?

**Comment by axcore** [comment]
It looks like the tidying code is broken. It will be fixed in the next release.

**Comment by axcore** [comment]
Fixed in v2.2.098. The code is only released to github/pypi for the moment.

If you are using MS Windows, you can download the source code, and then copy it over the top of the source code you already have, in **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube\**. (You might need to enable hidden hidden folders on your system first).
