### ISSUE TITLE
'Check Channel' downloads wrong thumbnail if you use custom titles

### ISSUE THREAD

**Issue by trinsic** [axcore/tartube#195]
### What operating system are you using?
Windows 10

### What version of Tartube are you using?
v2.2.117 from git source

### Problem
I've perhaps hit a bug but I'm not sure. I like to have the format available in the title so I can know quickly the quality I am dealing with e.g Title (720p).mkv. However when you run a check the thumbnails are downloaded and the highest quality video is used to grab the thumbnail e.g Title (2160p).jpg. When I then go to download I only want 720p so it downloads the thumbnails again and names them e.g Title (720p).jpg. I end up with both 2160p and 720p thumbnails.

The database gets confused and I end up with two of every video available inside Tartube (one as 2160p and another as 720p), the 2160p version is only a thumbnail and the file does not actually exist. Once I set the title in settings to just the default it works fine.

**Comment by axcore** [comment]
I have not checked your specific problem yet, but you should know that youtube-dl is broken due to major changes in the YouTube codebase. I am also seeing it fetch three copies of each video when checking a channel/playlist.

Your options at the moment are (1) switch to youtube-dlc, which is working a bit better, or (2) wait for a youtube-dl fix.

**Comment by trinsic** [comment]
Alright I'll put it down to that. I've checked out youtube-dlc and will switch it over soon.

Thanks for the app, works great.

**Comment by axcore** [comment]
Hopefully you already know [how to switch between youtube-dl forks](https://github.com/axcore/tartube#625-using-youtube-dl-forks).
