### ISSUE TITLE
customize icons location

### ISSUE THREAD

**Issue by legrostdg** [axcore/tartube#20]
How can I specify where tartube should look for its icons? I'd like to install the icons in /usr/share/tartube/icons/

**Comment by axcore** [comment]
The setup_pixbufs() function in mainwin.py handles that. 

I could add another environment variable, if that would be useful. That would give us

`TARTUBE_NO_UPDATES=1 TARTUBE_ICON_DIR=/usr/share/tartube/icons python3 setup.py build`

What do you think?

**Comment by axcore** [comment]
I suppose a better alternative suggestion would be to use a single environment variable, which disables youtube-dl updates, sets the icon location, and anything else you want:

`TARTUBE_DEBIAN=1 python3 setup.py build`

**Comment by legrostdg** [comment]
I think TARTUBE_ICON_DIR would be best, it could be useful for other users. I don't get how you install the icons for regular users, maybe I missed something?

**Comment by chanchu** [comment]
Related, when installing from pip on Linux, the program won't load unless running from a directory that contains the icons folder. 

> Traceback (most recent call last):
  File "/home/${USER}/.local/lib/python3.6/site-packages/lib/mainapp.py", line 890, in do_activate
  self.start()
  File "/home/${USER}/.local/lib/python3.6/site-packages/lib/mainapp.py", line 959, in start
    self.main_win_obj = mainwin.MainWin(self)
  File "/home/${USER}/.local/lib/python3.6/site-packages/lib/mainwin.py", line 365, in \_\_init__
    self.setup_pixbufs()
  File "/home/${USER}/.local/lib/python3.6/site-packages/lib/mainwin.py", line 426, in setup_pixbufs
    GdkPixbuf.Pixbuf.new_from_file(full_path),
GLib.Error: g-file-error-quark: Failed to open file '/home/${USER}/icons/win/system_icon_16.png': No such file or directory (4)

This is easily fixed by downloading the source and copy/pasting the folder wherever you plan on launching tartube from, but this prevents you from being able to run it from anywhere and is more of a bandage over the problem than anything. Could be an installation hiccup on my end?

**Comment by axcore** [comment]
> I don't get how you install the icons for regular users, maybe I missed something?
The simple answer is this: I wrote everything so that installation is not necessary. Just download the source code anywhere on your filesystem, then run the Tartube executable.

The advantages of this choice are:

1. The installer for MS Windows is a million times simpler
2. If the user download thousands of videos onto an external hard drive, which is connected to many computers, the user doesn't have to worry about installing Tartube on every computer. They only need one copy on the external hard drive

I will add TARTUBE_ICON_DIR today, and then we can see what's next.

**Comment by axcore** [comment]
> Related, when installing from pip on Linux, the program won't load unless running from a directory that contains the icons folder.

I have ready the documentation and I still have no idea how pip works.

**Comment by axcore** [comment]
Ok, I have a solution to these problems which I'll upload shortly, so please don't waste time coding your own :)

**Comment by axcore** [comment]
@legrostdg,

v1.1.008 looks for the icons in /usr/share/tartube/icons/ as well as in ../icons. I've added a global variable in the 'tartube' executable, specifying  /usr/share/tartube/icons/ as an alternative location. We can add new locations to that, if we create new packages. Hopefully that should be better than adding even more environment variables.

@chanchu,

The MANIFEST.in was not configured correctly, which might explain why pip doesn't install the icon files in the right place. I've uploaded a fix to pypi as v1.1.008, perhaps you can test it for me.

**Comment by chanchu** [comment]
Reinstalled through pip, currently getting the following error:

> Traceback (most recent call last):
  File "/home/${USER}/.local/bin/tartube", line 33, in <module>
    import mainapp
ModuleNotFoundError: No module named 'mainapp'

Sorry for not being able to provide much help, I'm not very familiar with pip packaging either :/
