### ISSUE TITLE
When saving window size, also save the position of separators/sliders within the window.

### ISSUE THREAD

**Issue by MohamedEssabani** [axcore/tartube#215]
Currently, it is possible to save the window size of the tartube window when closing. It would be helpful if this also saved the position of the separators within the window, e.g. between the list of folders and the list/grid of videos, between the top and bottom part of the progress tab, etc.

**Comment by axcore** [comment]
The position of the slider in the **Videos** tab is already saved, when the window size is saved. (Perhaps it is not working on MS Windows? I haven't tested that.)

**Comment by ceonelson** [comment]
On windows the vertical sliders between folders and grid doesn't seem to be saved.  Let me know if there's anything I can do to help you test :)

**Comment by axcore** [comment]
Ok, I'll investigate that. 

I thought that people wouldn't want the positions of the **Progress** and **Classic Mode** sliders to be remembered, but I can add that, if so.

**Comment by axcore** [comment]
Fixed in v2.3.020. The slider positions are remembered in all three tabs. I have tested them on MS Windows.

There is now a separate setting for remembering the position of sliders, **Edit > System preferences... > Windows > Main window > Also remember the position of main window sliders**

The fixed code is only uploaded to github and pypi. You can either wait for the next full release, or patch your installation by downloading the code from github, and copying it into **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube**. (You may need to enable hidden folders on your system first.)
