### ISSUE TITLE
Restart downloading

### ISSUE THREAD

**Issue by lsaranto** [axcore/tartube#218]
Can you add an option to the context menu to redownload a link (in Classic mode).

Currently, you have to copy the URL, delete it and then re-add it.

**Comment by axcore** [comment]
If the video is still visible in the bottom half of the **Classic Mode** tab, there is a re-download button just below that (fifth button from the left). Select one or more videos, then click the button.

**Comment by lsaranto** [comment]
If you mean the two arrows forming a circle, I just tried it (again). Nothing happens.

**Comment by axcore** [comment]
Yes, I'm seeing a python error when that button is clicked. I'll fix it shortly.

**Comment by axcore** [comment]
Fixed in v2.3.020. 

The fixed code is only uploaded to github and pypi. You can either wait for the next full release, or patch your installation by downloading the code from github, and copying it into C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube, replacing the code already there. (You may need to enable hidden folders on your system first.)

**Comment by candrapersada** [comment]
Why does the archive always reset when typing the re-download button to continue downloading the YouTube playlist without downloading from scratch again?
