### ISSUE TITLE
Duplicate db entries

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#225]
win10 / latest / no terminal error :D

I added a new playlist, then went to check it and it downloaded all the thumbnails and list of playlist items.  Then I applied custom download option of "audio only" (which has the file name slightly different since there's no resolution) to the playlist, then downloaded the playlist.

In the end 2 db entries were created for each item - one for when the item was checked, and a second for when the item was downloaded. On the filesystem there's only a jpg for the checked item, the downloaded item has all files (ie the jpg, metadata, and mp3 file).

Side note:
I reverted my database and renamed the filesystem folder so I could redo everything and make sure what I thought caused the issue actually did.

Then I reverted the db again, added the playlist, set dl opt "audio only" before checking, then dled just 5 of the 180 items to test it was correct (it was). Then I moved over the next valid file (#6) and did refresh playlist to see if it would see that the file was there and mark it as downloaded / link to the file. To my surprise it didn't. I tried adding that file's entry in the archive.txt and refreshed again but it still didn't show up.

How does the refresh work exactly? Is there an easy way to detect that the downloaded files are there?

Thanks!

**Comment by axcore** [comment]
>In the end 2 db entries were created for each item - one for when the item was checked, and a second for when the item was downloaded. On the filesystem there's only a jpg for the checked item, the downloaded item has all files (ie the jpg, metadata, and mp3 file).

I'm afraid this is expected behaviour. 

youtube-dl differentiates videos using the file name, not the URL. So, you can download a playlist, then change the file format (in **Edit > General download options... > Files > File names**), then download the playlist again, and you will have two copies of every video.

We can tell youtube-dl to use an archive file, so that the same URL is not downloaded twice **(Edit > System preferences... Operations > Downloads > Allow downloader to creates is own archive file...)**. Then, you can download the playlist as often as you want, using a different file format each time, and you will only have one copy of each video.

But, this behaviour only applies to _real downloads._ When you click Tartube's **Check all** button, you are telling youtube-dl to _simulate_ a download, and the archive file is not used. 

The only solution to your problem is to **Check** and **Download** a playlist using the same file format.

**Comment by axcore** [comment]
> How does the refresh work exactly? 

You can test it for yourself:

- In Tartube's main window, create an empty folder called **testme**
- Right-click the folder, and select **Show > Default location**
- The folder is opened on your desktop. Copy a video into this folder
- Now do the refresh, **Operations > Refresh database... **, or right-click the folder and select **Folder actions > Refresh folder**
- In the warning window, click **Yes**
- The video appears in Tarube's database

The full description of how the refresh operation works is this:

- Get a list of files in a folder
- Filter out everything which is not a video file
- Filter out duplicate videos (i.e. **ymca.mp4** and **ymca.avi** should only be counted once)
- Eliminate any videos which are already in Tartube's database
- If there are any videos left, add them to Tartube's database

I just noticed that refresh eliminates all audio files, so I will change that behaviour to **Filter out everything which is not a video or audio file**

**Comment by ceonelson** [comment]
Good to know the inner details, I was able to move over the already downloaded files (that had the name format I wanted) and ytdl recognized they were already downloaded when I did the playlist download.

So for the refresh it just adds those videos to the tartube database but I assume there's no association with the source URL (since you wouldn't be able to know that without it being in the filename or metadata)?

**Comment by ceonelson** [comment]
The "download" operation just finished and I noticed all the files that I had manually copied over were marked as "not new" - I figure this is the expected behavior?

**Comment by axcore** [comment]
> So for the refresh it just adds those videos to the tartube database but I assume there's no association with the source URL

That's right. If refresh adds a video to the database, the URL will not be known. 

The workaround is to **Check** a playlist first, before **Refresh**ing it. If Tartube already knows that **ymca.mp4** belongs to [https://www.youtube.com/watch?v=CS9OO0S5w2k](https://www.youtube.com/watch?v=CS9OO0S5w2k), then the refresh will update the database, rather than adding a new video to it.

>The "download" operation just finished and I noticed all the files that I had manually copied over were marked as "not new" - I figure this is the expected behavior?

Yes. A downloaded video is marked "new" until you watch it. When you manually copy over videos, Tartube doesn't know if they've been watched or not, so it assumes not.

You can mark any video(s), or even whole channels/playlists, as either New or Not New, any time you want.

**Comment by axcore** [comment]
Closed for inactivity.
