### ISSUE TITLE
keep progresses in list

### ISSUE THREAD

**Issue by urfausto** [axcore/tartube#231]
would it be possible to keep displayed rows in the list for the accomplished progresses? it seems that when one action is completed it deletes the old items in the progress tab.

**Comment by axcore** [comment]
Hi urfausto, why would you want to do that?

(By the way, it's already possible in the **Classic Mode** tab. Click the button in the top-right corner.)

**Comment by urfausto** [comment]
> Hi urfausto, why would you want to do that?

thought it could be a useful behaviour at first sight, with a 'delete history' button... to keep trace of your own actions.

**Comment by axcore** [comment]
Ok, I understood your intention, but I think it is not a good idea. Every time you change something in the database (for example, if you delete a video), the Progress tab must also be updated. So then Tartube needs two databases, and that means a lot of new code (and a lot of new bugs).

I considered writing a logfile, every time the progress list is updated. But this is also not simple: the Gtk library can crash when reading/writing files. Also, what happens if two copies of Tartube are writing to the same logfile, at the same time? That would require a lot of extra code, and even more bugs.

So, I will mark this one as `Won't fix`, and sorry to disappoint you :-)

**Comment by urfausto** [comment]
> and sorry to disappoint you :-)

ok thanks for the explanation... nevermind. tried my luck. :rofl:

**Comment by axcore** [comment]
Did you know that you can drag and drop that list into another window, for example a text editor? (I don't know if that will be useful, or not.)

**Comment by urfausto** [comment]
> for example a text editor

hm interesting... i will save this trick, thanks.

**Comment by axcore** [comment]
Click **Edit > System preferences... > Windows > Drag** to set what data is copied during a drag and drop.
