### ISSUE TITLE
Custom forks not working?

### ISSUE THREAD

**Issue by DankMemeGuy** [axcore/tartube#254]
Due to https://github.com/blackjack4494/yt-dlc/issues/296 I have tried to use https://github.com/pukkandan/yt-dlc instead

In the Downloaders > Forks > I put "yt-dlc" however when performing the download I get an error. I'm wondering if this is due to that fork just not being compatible, or is Tartube having error pulling that fork?

**Comment by axcore** [comment]
The fork is now called [yt-dlp](https://pypi.org/project/yt-dlp/).

**Comment by candrapersada** [comment]
> In the Downloaders > Forks > I put "yt-dlc" however when performing the download I get an error. I'm wondering if this is due to that fork just not being compatible, or is Tartube having error pulling that fork?

because how to install and use yt-dlc is not the same, issue [#243](https://github.com/axcore/tartube/issues/243#issuecomment-764900724) 
![youtube-dlc](https://user-images.githubusercontent.com/36833664/105408548-b00a9a00-5c61-11eb-9bb4-c4405a9e9adc.PNG)
https://pypi.org/project/yt-dlp

[DESCRIPTION](https://github.com/pukkandan/yt-dlp#description)
![image](https://user-images.githubusercontent.com/36833664/105408054-0fb47580-5c61-11eb-8a75-92e16233cb2a.png)
https://github.com/pukkandan/yt-dlp/releases

**Comment by axcore** [comment]
Ok, in that case, the authors of yt-dlp need to update their code to use one name instead of two. Until they do that, yt-dlp is not compatible with youtube-dl or Tartube.

**Comment by DankMemeGuy** [comment]
Just wondering if this was ever fixed? I read through https://github.com/pukkandan/yt-dlp/issues/34 and still unsure. It seems like it still doesn't work when I put yt-dlp?

**Comment by axcore** [comment]
I am under the weather, so it will be a week or two before I can complete https://github.com/pukkandan/yt-dlp/issues/34.

**Comment by pukkandan** [comment]
I'll make sure to fix pukkandan/yt-dlp#34 by next release (not today's)

**Comment by pukkandan** [comment]
This has been fixed from my end

**Comment by axcore** [comment]
Support for yt-dlp is added in v2.3.110. It seems to be working well.
