### ISSUE TITLE
why are there no Uninstalling/removing packages youtube-dl(c)

### ISSUE THREAD

**Issue by candrapersada** [axcore/tartube#255]
why are there no Uninstalling/removing youtube-dl(c) from `Operations`?
![image](https://user-images.githubusercontent.com/36833664/105762494-0ee45200-5f87-11eb-8e84-9221f55c6490.png)

**Comment by axcore** [comment]
Same answer: it is the user's responsibility to install and uninstall software on their system.

Installing youtube-dl and updating youtube-dl via pip are exactly the same, so I allow that

Installing FFmpeg on MS Windows is also allowed, because 99.99% of users don't know how to install it

Otherwise, Tartube doesn't install/uninstall anything
