### ISSUE TITLE
Missing icons in Classic Mode and Failing downloads when moving Tartube Portable folder to another location

### ISSUE THREAD

**Issue by strx5** [axcore/tartube#260]
Greetings! 
Basically, the title says it all! Below is an Imgur link to a screenshot:

[tartube classic mode](https://imgur.com/KLCyIm8)

As for the errors I get when I try downloading videos after relocating Tartube 64bit Portable folder to, say, another drive, they are just some general status errors. The Output tab  doesn't provide any details:

``youtube-dl --newline -i --hls-prefer-native -o C:/webdl/_DL/%(title)s.%(ext)s --cookies C:/webdl/_DL/cookies.txt -f bestvideo[height<=?1080]+bestaudio/best[height<=?1080] --merge-output-format mkv --verbose https://www.youtube.com/watch?v=PDcFOOnMAIQ ``

Debugging is not available as well. Running Windows 7 x64. It appears the portable version is not quite portable in my case as if some pathes were _absolute_ instead of _relative_.

Also, there's another minor annoyance with Tartube [not recognizing](https://i.imgur.com/MxEXMUW.jpeg) cyrillic characters as it fails to display them correctly in the list on the Progress tab

**Comment by axcore** [comment]
Can you please run Tartube from inside a terminal window. I am guessing that python is spitting out a lot of errors, and that's why you are having so many problems.

The method is described [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work). For the portable addition, open the `tartube` folder (wherever you've copied it), then run `mingw64.exe` in that folder, and in the terminal window type 

```
cd /home/user/tartube
python3 tartube/tartube
```

**Comment by strx5** [comment]
Axcore, I've finally got back at my desktop. So, I attached the terminal output in a txt-file.
[mingw64 output.txt](https://github.com/axcore/tartube/files/6014434/mingw64.output.txt)
I have also updated the link to the screenshot showing poor font handling. 

It appears, if I move the folder to another location, not only have I to redownload the required components, but also all the settings eventually get messed up, however not all of them revert to defaults. This means the portable version is rather 'unpacked' then truly portable. I hope you'll look into these issues and come up with a solution

**Comment by axcore** [comment]
Ok, I tested `tartube-portable-64bit.zip` on a clean installation. I copied the file to the desktop, extracted it, ran Tartube, installed youtube-dl and ffmpeg, and sucessfully downloaded a [video](https://www.youtube.com/watch?v=jNQXAC9IVRw). 

I am having the same problem: some icons are not visible. Not sure what the problem is, but as a workaround, you can switch from the standard Gtk icons to a custom set, which do work (Edit > System preferences... > Windows > Main window, enable **Replace stock icons with custom icons**)

Then I deleted the video, copied the whole folder to a different drive, and re-downloaded the same video, without problems. I'm not sure what is causing your download problems. Other people have, in the past, experience problems with external drives, and I still don't know what the cause is. Could be a python problem, or a Gtk problem, or MSYS2, or Windows itself, or even my code that's at fault. If you have not already done so, make sure the Tartube (portable) folder, and the folder into which you're downloading videos, are on the same hard drive; that might help a bit.

I can't reproduce your problem with cyrillic text, but it might be the same issue mentioned [here](https://github.com/axcore/tartube/issues/251) and in several other tickets. I'm still not sure what can be done about it.

Your text file does not contain any python errors. I'm not sure where the ! ! ! comes from, hopefully you added that yourself.

**Comment by axcore** [comment]
The MS Windows installer for v2.3.110 contains more locale stuff, it's possible that it might fix your Cyrillic problem. Perhaps you can test it, and tell me what happens.

**Comment by overgeeked** [comment]
I've had similar issues with these errors:

(tartube:80780): Gtk-WARNING **: 14:36:39.508: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node arrow owner GtkNotebook)

(tartube:80780): Gtk-WARNING **: 14:36:39.518: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node arrow owner GtkNotebook)

(tartube:80780): Gtk-WARNING **: 14:36:39.525: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner GtkNotebook)

(tartube:80780): Gtk-WARNING **: 14:36:41.875: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node arrow owner GtkNotebook)

(tartube:80780): Gtk-WARNING **: 14:36:41.877: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node arrow owner GtkNotebook)

(tartube:80780): Gtk-WARNING **: 14:36:41.879: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner GtkNotebook)

(tartube:80780): Gtk-WARNING **: 14:36:42.686: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node arrow owner GtkNotebook)

(tartube:80780): Gtk-WARNING **: 14:36:42.689: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node arrow owner GtkNotebook)

(tartube:80780): Gtk-WARNING **: 14:36:42.690: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner GtkNotebook)

(tartube:80780): Gtk-WARNING **: 14:42:41.634: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner GtkNotebook)

**Comment by overgeeked** [comment]
> I've had similar issues with these errors:
> 
> (tartube:80780): Gtk-WARNING **: 14:36:39.508: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node arrow owner GtkNotebook)
> 
> (tartube:80780): Gtk-WARNING **: 14:36:39.518: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node arrow owner GtkNotebook)
> 
> (tartube:80780): Gtk-WARNING **: 14:36:39.525: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner GtkNotebook)
> 
> (tartube:80780): Gtk-WARNING **: 14:36:41.875: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node arrow owner GtkNotebook)
> 
> (tartube:80780): Gtk-WARNING **: 14:36:41.877: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node arrow owner GtkNotebook)
> 
> (tartube:80780): Gtk-WARNING **: 14:36:41.879: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner GtkNotebook)
> 
> (tartube:80780): Gtk-WARNING **: 14:36:42.686: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node arrow owner GtkNotebook)
> 
> (tartube:80780): Gtk-WARNING **: 14:36:42.689: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node arrow owner GtkNotebook)
> 
> (tartube:80780): Gtk-WARNING **: 14:36:42.690: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner GtkNotebook)
> 
> (tartube:80780): Gtk-WARNING **: 14:42:41.634: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner GtkNotebook)

******** UPDATE ********
This issue was resolved for me by following the suggestion:
https://github.com/axcore/tartube/issues/118#issuecomment-653762359

"Click Edit > System preferences... > Windows > Main window > Replace stock icons with custom icons, then restart Tartube."

**Comment by axcore** [comment]
Issue closed for inactivity. For some time, custom icons have been the default, so few users should run into any problems.
