### ISSUE TITLE
Rate Limit Simulated Downloads/Checking

### ISSUE THREAD

**Issue by Sushiman42** [axcore/tartube#261]
I run into youtube-dl and youtube-dlc errors upon checking, and even with a sleep interval set, the simulated downloads run into rate-limits on longer youtube playlists. Is there any way to set a sleep interval for the checking/simulated dl process?

**Comment by axcore** [comment]
There is a youtube-dl option that sets a minimum delay between downloads. It is set here:

Edit > General download options... > Name > Show advanced download options (if visible)
Click OK to close the window
Edit > General download options... > Advanced > Workaround
Set **Minimum seconds to sleep before each download**

However, it seems that youtube-dl ignores it, when performing a simulated download (that's what happens when Tartube 'checks' a playlist)

So your only choice is to use one of the other options. For example, you could set **Edit > General download options > Downloads > Playlists > Stop downloading playlist at index**, using a number that isn't too big.

**Comment by Sushiman42** [comment]
Looks like you're correct, it's on youtube-dl's end. [This commit should add an option once merged](https://github.com/ytdl-org/youtube-dl/pull/28144). Thanks.
