### ISSUE TITLE
Tartube only downloading thumbnails, not actual video files

### ISSUE THREAD

**Issue by AtlasC0R3** [axcore/tartube#265]
### What operating system are you using?
Debian (Parrot OS distro)

### What version of Tartube are you using?
Tartube v2.3.085, installed with `*.deb` file

### What happens when you run Tartube from a terminal window?
Nothing entirely relevant:
```
(tartube:8065): Gdk-CRITICAL **: 15:57:49.407: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

So, straight to the point, Tartube does not download videos. I tried multiple videos, youtube-dl, youtube-dlc, really everything I could find, nothing.
*videos i tried were https://www.youtube.com/watch?v=XI9Zsh4DNpI, https://www.youtube.com/watch?v=zGYNsW-RJsM, https://www.youtube.com/watch?v=zrrs9LGIfyQ weird tastes i know shhhhh*

The only way I found that worked was Classic Mode, which is inconvenient: half of Tartube not working at all.
This probably is a fault on my side, I just don't know what to do anymore.

Oddly enough, if I copy-paste all of the commandline arguments from the Output tab into a `youtube-dl.conf` file in my `~` directory, youtube-dl will happily work.

**Comment by axcore** [comment]
Click the **Videos** tab, and try to download a video (any video).

When it fails, click the **Output** tab, and show me a screenshot of that tab, so we can see what's going on. (You could also copy-and-paste the text inside the tab, if a screenshot is not convenient).

>The only way I found that worked was Classic Mode

The **Videos** and **Classic Mode** tabs use a different set of download options (by default), so that might explain your problem. I can tell you definitively once I've seen the screenshot.

**Comment by Lod3** [comment]
@AtlasC0R3 I had the same issue on windows, try and reset your settings to default. I changed the format settings to these and it resolved it: 
![python3_KMdyTfIKLD](https://user-images.githubusercontent.com/14292591/109283892-8ffd6600-781f-11eb-9271-000575640df1.png)

**Comment by AtlasC0R3** [comment]
Er, nevermind. Apparently deleting tartube's config file (`~/.config/tartube/`) fixed the issue. Weird.
Sorry for any time wasted.
