### ISSUE TITLE
FFmpeg installation fails?

### ISSUE THREAD

**Issue by BruhMoment2000** [axcore/tartube#270]
Hi, I'm getting this message when setting up Tartube and installing FFmpeg (I just installed Tartube for the first time). Everything seems to be working fine, what should I do?
![Screenshot 2021-03-01 153249](https://user-images.githubusercontent.com/79851739/109505370-327a4b00-7aa5-11eb-959c-25921bc11c68.png)

**Comment by axcore** [comment]
I'm investigating it now.

**Comment by axcore** [comment]
**Note: this is a problem on MS Windows only, Tartube v2.3.110 only.**

I have the problem. I cannot explain why FFmpeg fails to install during Tartube setup, because it installs without problems from the command line. (The two should be exactly the same).

Here is the workaround:

- Enable 'show hidden folders' on your computer (in system settings)
- Open the folder **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\**
- Open the terminal window by double-clicking the application **mingw64.exe** 
- In the new terminal window, type the following command:

`pacman -S mingw-w64-x86_64-ffmpeg`

**Comment by BruhMoment2000** [comment]
Thanks!

**Comment by axcore** [comment]
FFmpeg can now be installed in the normal way. There is no need to update Tartube again.

(I have tested it on two different machines.)

![ffmpeg2](https://user-images.githubusercontent.com/37951926/110351822-1fc7bf00-802d-11eb-8595-d76b542e062f.png)

**Comment by q2051839** [comment]
> **Note: this is a problem on MS Windows only, Tartube v2.3.110 only.**
> 
> I have the same problem. I cannot explain why FFmpeg fails to install during Tartube setup, because it installs without problems from the command line. (The two should be exactly the same).
> 
> Here is the workaround:
> 
>     * Enable 'show hidden folders' on your computer (in system settings)
> 
>     * Open the folder **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\**
> 
>     * Open the terminal window by double-clicking the application **mingw64.exe**
> 
>     * In the new terminal window, type the following command:
> 
> 
> `pacman -S mingw-w64-x86_64-ffmpeg`

error: mingw-w64-x86_64-libvorbis: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
