### ISSUE TITLE
Edit System command to add or delete arguments 

### ISSUE THREAD

**Issue by Collin8000** [axcore/tartube#276]
Can you please make it so we can edit the system command for youtube-dl to add or delete youtube-d  arguments.
I have the latest version and i have read the README, i am using ubuntu 20.04 with the latest version of yt-dlp

**Comment by axcore** [comment]
You can add as many options as you like in **Edit > General download options > Name**, in the box marked **Extra command line options**.

**Comment by Collin8000** [comment]
yt-dlp --external-downloader axel --extract-audio --audio-format opus --get-id "https://www.youtube.com/playlist?list=PLvBcwlEaMO-Jxt9DvlHRicxd09i4ciKYq" | xargs -I '{}' -P 25 youtube-dl 'https://youtube.com/watch?v={}'

**Comment by axcore** [comment]
Added in v2.3.135. The new functionality is marked as **EXPERIMENTAL**, because the yt-dlp command you specified above no longer works (even when using yt-dlp from the command line).

Click **Edit > General download options...**, then in the new window, click the **Show advanced download options** button if it's visible.

![experimental](https://user-images.githubusercontent.com/37951926/119236666-9fdfca00-bb30-11eb-894f-d491429d5c97.png)
