### ISSUE TITLE
Add support for yt-dlp's --paths parameter

### ISSUE THREAD

**Issue by 1024mb** [axcore/tartube#299]
Could you please add an option to use that? I use Classic Mode and using `--paths` to point to a temp folder would be great. Please add that option.

The way I think it could be added is with a box to specify the temp folder and another to specify the home path though if we are already choosing a download folder Tartube could just use that as the home path and only let us specify the temp one.

Another way could be just adding a box to disable or override the output directory option so it only passes the filename pattern as `--output` that way we can add in the Extra Command Line Options box the `--paths` parameter (if we add it now yt-dlp will ignore it because Tartube is passing a full path with the `--output` parameter). I prefer to do it this way so you don't have to maintain so many options.

**Comment by axcore** [comment]
Added in v2.3.233. 

Click **Edit > General download options...**. Click the **Show advanced download options** button if it's visible. Then click **yt-dlp > Output** or **yt-dlp > Paths**.

The interface isn't exactly what you suggested, but hopefully it meets your needs. If not, there is still time to tweak it before the next major release.

**Comment by 1024mb** [comment]
Thank you!! It's much better than what I suggested.

One thing I want to ask you, I saw you let us use --break-on-existing but there is no way to customize the archive file path, can this be added?

**Comment by axcore** [comment]
> EDIT1
>-There is also another thing. I've picked yt-dlp and choose a custom executable and when I click on "Update yt-dlp" in Classic mode I get this:

I am not able to reproduce this problem. Please show me the settings you have selected in **Edit > System preferences > Downloads > Forks** and **Downloaders > File Paths**, so I can make sure I'm trying the same setup.

**Comment by axcore** [comment]
In v2.3.447, you can fully customise the location of the archive file. See Edit > System preferences... > Operations > Archive

**Comment by ceonelson** [comment]
My issue is that I have a fair amount of files that I get errno 2 on when trying to download (I think it is because of a path length issue), but I found that if I set the TEMP folder it can download them successfully then move them to the proper spot.

But as far as I can tell, I will have to have custom download options for each folder so I can set the proper HOME path to make sure the files end up in the right spot.

How can we tell Tartube to use the current working folder for the HOME path?

Thanks Axcore!

**Comment by axcore** [comment]
>My issue is that I have a fair amount of files that I get errno 2 on when trying to download (I think it is because of a path length issue), but I found that if I set the TEMP folder it can download them successfully then move them to the proper spot.

>But as far as I can tell, I will have to have custom download options for each folder so I can set the proper HOME path to make sure the files end up in the right spot.

Is this Windows stuff? I'm not a Windows programmer, I don't understand how that would be done.

>How can we tell Tartube to use the current working folder for the HOME path?

You can't, the 'current working directory' does not exist, it is just an abstraction. (There is a python `os.getcwd()` function, but it won't give you what you want, every time.)

If path length is an issue you can try these things:

1. Right-click a channel, and select **Channel actions > Set download destination > Use an external location**. You can probably add HOME there. (I have not tested that.)

You must still update every channel/playlist in your database, but at least you won't have to create new download options every time2. 

2. The obvious solution: download to C:\stuff rather than C:\folder\folder\folder\folder\stuff

3. Limit the filename length. **Edit > General download options... > Files > Filesystem > Limit filename length**. But beware, this seems to be broken in yt-dlp at the moment.

**Comment by warrigt** [comment]
Am I able to use %(upload_date>%Y)s somehow for the path?

**Comment by axcore** [comment]
Edit > General download options  > Files > File names

In the box at the top, select "Custom"

Now you can select the upload date in the boxes near the bottom
