### ISSUE TITLE
I installed FFmpeg and tar tube not only fails to detect it but it won't let me choose the location of the .exe file.

### ISSUE THREAD

**Issue by strunberg** [axcore/tartube#31]
![uyguyguyguyi](https://user-images.githubusercontent.com/6355904/70380218-8da2a980-1905-11ea-90e5-76cd1ed4b212.png)

Whenever I attempt to change the location of FFmpeg in the options it reverts back to the default settings.

I even tried to get arround this issue by placing FFmpeg in the tar tube's directory and it still won't use FFMPEG

**Comment by axcore** [comment]
Ok, there are two problems here:

1. The user can't set a new FFmpeg location

Actually, this window is displaying the wrong value for the FFmpeg location; using the 'Set' button does work, even though the user can't see the change. The window will be fixed in the forthcoming release.

2. Tartube doesn't use FFmpeg

I suspect this is a fault with youtube-dl, not with Tartube. Other people have complained about the same issue on the youtube-dl page, but I never hear back from them.

**Comment by strunberg** [comment]
I came across a GUI program for Youtube-DL called "YDL_UI_v2.6.3_Portable".

What's special about it is that it comes with FFMPEG so a user doesn't have to install it.

Would you be willing to release a portable version of your program that would come with FFmpeg so users won't run into issues?

I really like your program the best due to it's channel auto downloader, but for many including myself we're running into the issue of not being able to download due ffmpeg not installing correctly.

I would like to start archiving channels in 1080p due how the recent rule changes are making everyone worried about the future of their channels, I myself think that things are going to get WAY worse as we approach the elections.

**Comment by axcore** [comment]
I'm working on a few serious bugs. I can't release a new version of Tartube until they are fixed. This will likely take a few days.

Because of the FFmpeg issue, and because your favourite YouTube might disappear at any moment, I recommend using something else to download your 1080p videos. It looks like YDL_UI, youtube-dlg and the command-line version of youtube-dl all recognise FFmpeg, so you can choose any of them.

(Tartube is a fork of youtube-dlg, so perhaps that is the best choice).

Once you have the videos, you can incorporate them into Tartube's database. For example, if you wanted a complete backup of pewdiepie's channel:

1. Download videos from the channel using any of the applications listed above
2. In the Tartube main menu, click Media > Add channel..., and add pewdiepie
3. Do a 'Check all' operation (click the button in the bottom-left corner). Alternatively just check the channel, by right-clicking pewdiepie on the left side of the window, and selecting 'Check channel'
4. Move the downloaded videos into the Tartube folder
5. From the main menu, click Operations > Refresh database

Note that the 'refresh database' operation is one of the things that isn't working perfectly at the moment.

On MS Windows, the Tartube installation is already portable. All the code is copied into a single folder; you can copy that folder anywhere, and Tartube will run as if it hadn't been moved. 

It is probably possible to add FFmpeg to that installation. I have already tried the obvious method, but it didn't work. I will try again, though.

**Comment by axcore** [comment]
Apparently, FFmpeg has recently been added to MINGW64, so you can install it without waiting for the next Tartube release.

1. Open the folder C:\Users\YOURNAME\AppData\Local\Tartube\msys64
2. Run the mingw64.exe application
3. Type this command into the new terminal:

pacman -S mingw-w64-x86_64-ffmpeg

4. Close the terminal
5. In Tartube, Edit > System preferences > youtube-dl > Path to the ffmpeg/avconv binary > Click the 'Reset' button

Try that, and tell me if it works for you.

**Comment by strunberg** [comment]
mingw64.exe is not in the msys64 folder.

**Comment by axcore** [comment]
> mingw64.exe is not in the msys64 folder.

Yes, that's why I deleted the comment.

Never mind, FFmpeg is now working on MS Window, and installing it is a one-click operation. Release tomorrow or on Friday.

file:///home/ra/Desktop/ffmpeg2.png

**Comment by axcore** [comment]
All fixed in v1.3.0. Click **Operations > Install FFmpeg** to install a compatible version of FFmpeg.

If you have any problems with this, feel free to re-open the issue.
