### ISSUE TITLE
Can't download age-restricted videos

### ISSUE THREAD

**Issue by Princefrogg4** [axcore/tartube#310]
### What operating system are you using?
Windows 10

### What version of Tartube are you using?
v2.3.110

So the problem is universal with any age-restricted video I've tried. I tried adding my account details into Tartube but the video doesn't download and in the "errors/warnings" tab, I get the following messages:
ERROR: Sign in to confirm your age
This video might be inappropriate for some users
WARNING: Unable to look up account info: HTTP Error 400; Bad Request
WARNING: unable to download video info webpage: HTTP Error 404; Not Found

I also tried different websites and it doesn't work on them either anymore where I could download videos in the past.

**Comment by axcore** [comment]
This is a youtube-dl issue. The problem has been fixed, but there has not been a new release since June, so no-one is using the fix.

yt-dlp has been updated, so you can switch to that if you're using Linux. On MS Windows, Tartube can't install yt-dlp at the moment. The fix for that is already available from Github, or you can wait for the full release at the end of this month.

**Comment by axcore** [comment]
Yes, the latest releases of Tartube can install yt-dlp on all systems.
