### ISSUE TITLE
External Paths not saving

### ISSUE THREAD

**Issue by Indochild56** [axcore/tartube#329]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 10

### What version of Tartube are you using?
2.3.332

I'm trying to set an external folder for a specific channel, but when i go to set and find the folder and click open, it just leaves the path blank. I've tried saving to multiple different external folders, but none of them take.

**Comment by axcore** [comment]
Fixed in v2.3.351. 

The update is only on github at the moment, so you need to download the source code from here and use it to replace the source code in your installation, which is typically `C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube\`

Or just wait for the next main release, as the MS Windows installer isn't updated yet
