### ISSUE TITLE
ffmpeg hang when processing files for splitting

### ISSUE THREAD

**Issue by alidan** [axcore/tartube#330]
Was going to add this as a question but then I found what I was doing wrong for some videos

it appears that if you have these settings and dont have a description (video is here so you can see the description https://www.youtube.com/watch?v=WktBkffgEm8) ffmpeg hangs till you kill the program. 

I think a fix for this would be a fall back if there are no clips found.

On a side note, adding the clips one by one works, however im wondering if there is a way to parse a block of text at a time rather than individually for both time and title? at the very least most youtube videos that time stamp will have a list of timestamps making individual entering a little tedious. I assume that videos have metadata/description files, would it be possible to have a button to open that up so we can paste in the description when i'm assuming ytdl fails to catch it? that way we can get the full clip lost in one go. 

also, when adding clips and titles, the titles did not show up at all. 
![python3_2021-08-25_19-12-36](https://user-images.githubusercontent.com/2681758/130880250-c7d264fb-0713-4858-b954-5bd5ab74ebf8.png)

small things aside, this helped me immensely, thank you for the update.

**Comment by axcore** [comment]
Sorry for your problem, I'm away from my desk for several weeks so might not be able to test the error for a while.

In the meantime, I suggest downloading the description file, then removing it later if you don't want it (Operations > Tidy up files...)

There is no general parsing facility. However, Tartube can read both metadata and description files, in order to extract a list of timestamps. For example, right-click a video and select Show video > Properties > Timestamps > Reset list using video description. To do this automatically, in the main window click Edit > System preferences > Operations > Clips, and enable the settings there.

**Comment by axcore** [comment]
Regarding the missing clip titles, if you have the URL of the video with missing titles, then I can check that video specifically (sooner or later).

**Comment by alidan** [comment]
in regard to missing titles, the titles are there, when processed it added them correctly, however in the viewer it showed nothing. 

ill get a few other videos that I want to split going and see if I keep having issues with those two things I can do, however I should have the program grab all the metadata and description but it wasn't doing that for some reason, which is why I was wondering about a fallback of some sort to add multiple time stamps at the same time manually from a single paste.

**Comment by axcore** [comment]
The missing titles are fixed in v2.3.549. (They are extracted correctly, the only problem was that the window did not display them.)

You can now copy and paste the video's description into a box, and Tartube will extract the timestamps (which is what you asked for). In the video properties window, click the timestamps tab, then click the **Reset list using copied text** button, then drag and drop (or copy) the video's description into the new window.

v2.3.549 also fixes some other related issues.
