### ISSUE TITLE
HTTP error 429: I can't download or check videos in 2.3.332

### ISSUE THREAD

**Issue by metapea** [axcore/tartube#331]
### What operating system are you using?
7

### What version of Tartube are you using?
The newest version

### What happens when you run Tartube from a terminal window?
I keep getting HTTP error 429 when downloading or checking on the newest version of tartube when using YouTube-dl or YouTube-dlp in version 2.3.332, unlike in 2.3.110, where downloading and checking videos still works fine.

Edit: when i tried to roll back to 2.3.110, i keep getting _"failed to load the tartube database file"_ until i deleted _''tartube.db''_, the video library is gone after deleting but i can downloads videos again unlike v3.332

Edit 2: i tested 2.3.332 with a deleted _''tartube.db''_. That still didn't download or check, the error from the newer version of tartube and not the database

**Comment by axcore** [comment]
Everyone is seeing the 429 error frequently; it's because of a change in YouTube's software. Make sure the archive file is enabled (Edit > System preferences > Operations > Downloads > Allow downloader to create its own archive file...)

Try enabling pauses between video downloads, that might help a bit (Edit > General download options > Name > Show advanced download options, then click the Advanced > Workaround tab, and set the sleep options)

Tartube cannot read databases from future versions (2.3.110 cannot read 2.3.332). If you need to rollback, you can find backups of the database file in Tartube's data folder, in the **.backups** folder.

**Comment by metapea** [comment]
- Allow downloader to create its own archive file...
It is.

- Advanced > Workaround tab, and set the sleep options
didn't work

**Comment by axcore** [comment]
The solution to the HTTP 429 error is to pass cookies, or solve the CAPTCHA.

[HTTP Error 429: Too Many Requests or 402: Payment Required](https://github.com/ytdl-org/youtube-dl#http-error-429-too-many-requests-or-402-payment-required)

Forcing IPV4 might also help, as described [here](https://askubuntu.com/questions/1220266/youtube-dl-do-not-working-http-error-429-too-many-requests-how-can-i-solve-this).
