### ISSUE TITLE
Please don't install this software at all.

### ISSUE THREAD

**Issue by awaixjvd** [axcore/tartube#347]
I was trying to find a good YT mp3 downloader and that's how i came across this software. My review is "please don't install this software at all". Let me explain why?

Luckily i chose to install the software in manual location (C:\Tartube) and initially the unzip process gave me a 352mb of software which was enough to raise an eyebrow. This is a fairly large size for a YT mp3 downloader. The competition for this are giving it in under 100mb. Anyhow, i proceeded with the installation and it had to download some ffmpeg codec (although i have vlc and k-lite mega codec pack) but again i thought it might have not been able to find the codecs so i went ahead to give permission to download and install the codec. 
It took 10mins to download (don't know why) and then half hour to install the software (on SSD) and finally (luckily) i checked the size of folder (c:\Tartube) and it was 1.57gb. SERIOUSLY? A YT downloader with a few codecs will take 1.57gb of disk space? What it is running in the background? I uninstalled it instantly. 

I would never recommend this software. Please try finding alternatives to this BUT NOT THIS.

**Comment by axcore** [comment]
>initially the unzip process gave me a 352mb of software which was enough to raise an eyebrow. 

Tartube is a Linux application ported to Windows. When you install Tartube on Windows, you're installing not just the app, but a miniature Linux environment, the Gtk graphics libraries and everything else needed to run a python GUI. That amounts to about 350 GB, of which Tartube itself only takes up about 5 GB.

It's unfortunate, but the Gtk people seem to have no interest in Windows, so we're stuck with the tools we have.

> it had to download some ffmpeg codec (although i have vlc and k-lite mega codec pack)

It's not a codec, it is software to convert one audio format to another. YouTube doesn't offer MP3 downloads, but everyone wants MP3 downloads, so we need something to convert from one format to another. If you're happy listening to your music in .m4a format then you don't need FFmpeg at all.

Again, it's unfortunate that the FFmpeg download is so big, but there seems to b e nothing that can be done to reduce its size.

>A YT downloader with a few codecs will take 1.57gb of disk space? What it is running in the background? 

The script I use to create the installers is available [here](https://github.com/axcore/tartube/blob/master/nsis/tartube_install_64bit.nsi). It contains simple instructions so that suspicious people can create their own installers, and compare them with mine to make sure there is no funny business going on.

>I would never recommend this software. Please try finding alternatives to this BUT NOT THIS.

As you say, on Windows Tartube is not the best choice for a pure MP3 downloader, especially if you're running it on a removeable drive.

**Comment by axcore** [comment]
Closed for inactivity.
