### ISSUE TITLE
A feature that makes it a breeze to backup & move a collection to other storage.

### ISSUE THREAD

**Issue by strunberg** [axcore/tartube#350]
It would be nice if you could use a GUI interface to move everything including the settings & videos to another hard drive in case one is failing.

**Comment by axcore** [comment]
There are two saved files, Tartube's config (settings) file and the database file, which stores a list of videos.

The database file (`tartube.db`) can be found in the same folder as your videos. Move that folder anywhere you like. Then, just tell Tartube where you've moved it (File > Database preferences > Add new database)

As for the config file (settings.json), if you move it somewhere else, how will Tartube find it? How will any applications find their config files, if they have been moved to some random location? (The answer is that they can't, that's why config files are all stored in one place).

On MS Windows, you probably want to use the portable version of Tartube, because it stores the config file in the same location as the source code. Then, you can just copy Tartube's installation folder anywhere you like. On Linux you could do the same thing by running Tartube's source code, as described [here](https://github.com/axcore/tartube#5310-run-without-installing).

The correct locations for the config file can be viewed in Edit > System preferences > Files > Config
