### ISSUE TITLE
Why does it download/prefer webm over mp4?

### ISSUE THREAD

**Issue by kibbblz** [axcore/tartube#370]
I've noticed that mostly the mp4 videos are always bigger in size so why does Tartube prefer webm? I think also even the mp4 downloads are faster.

**Comment by axcore** [comment]
If you don't specify a video format, then it is youtube-dl (not Tartube) which chooses the format (as far as I know; perhaps it is YouTube itself which uses .webm as the default).

**Comment by kibbblz** [comment]
The thing is, when I select mp4, it seems to download the smaller mp4 (30 fps) version. When I use this youtube downloader extension on Firefox, I see different formats and a bigger mp4 size thats 60fps which it downloads the audio and video file separately then merges them when done. I was hoping Tartube/youtube-dl could get the best quality/higher fps version of mp4. I just don't know how. Ive tried everything .. .so many options in Tartube though it gets overwhelming for me.

**Comment by vertigo220** [comment]
I know this is old and closed, but in case anyone else happens upon it, I did some comparisons with multiple videos a while back and found webm to generally be better quality than mp4 as well, which was frustrating because I'd assumed the opposite and downloaded a bunch of stuff specifically in mp4.
