### ISSUE TITLE
Unable to update yt-dlp to unthrottle downloads. 

### ISSUE THREAD

**Issue by strunberg** [axcore/tartube#390]
When updating to switch I get this error.

Here is the error log since it maxed out the character limit.

https://pastebin.com/g5WeybhN

**Comment by axcore** [comment]
Because you didn't tell me the version of Tartube that you are using, I suspect that you are using an old version. Please make sure you have v2.3.447.

Also, you can try uninstalling then reinstalling Tartube, which sometimes helps when updates from the PyPI or MSYS2 software repositories get broken.

**Comment by strunberg** [comment]
> Because you didn't tell me the version of Tartube that you are using, I suspect that you are using an old version. Please make sure you have v2.3.447.
> 
> Also, you can try uninstalling then reinstalling Tartube, which sometimes helps when updates from the PyPI or MSYS2 software repositories get broken.

How would one update the software?
