### ISSUE TITLE
No Link filter / batch reload info

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#420]
So the reload info from JSON button is awesome!! I've been using it to go through and fix the videos with UTF errors as I come across them and it has been working great!

The other thing I've been doing with it is finding videos that are downloaded but have "no link" shown, and to my delight reloading the info populates the link and all of the other missing information from them!

- Would it be possible to have a search filter that allows us to find videos with no id and/or url? 
- And then ideally a button that would reload the JSON for all of the videos in that view?

Also, there are some videos that only have the source link set but have actually been downloaded. When I go to properties and point it to the video file, it updates some information, but I still need to manually click the reload info button right after to have the "listed as" video name populated as well as the video downloaded and video unwatched checkbox. The top video name portion is never populated, it stays as (video with no name).

What do you think about having the reload info function called automatically when the video file for an item is updated?

Thanks Axcore!

**Comment by axcore** [comment]
I think there isn't room in the toolbar at the bottom of the Videos tab for yet another filter. 

In v2.4.031 you can right-click video(s) and select **Special > Reload metadata**. It doesn't do any harm to load metadata several times for the same video, so I suggest you apply the **Show undownloaded** filter, select all the videos (CTRL + A) then reload metadata for all of them.

>What do you think about having the reload info function called automatically when the video file for an item is updated?

That already happens. I've changed the code so that the entire window is re-drawn when either of the two buttons is clicked; this should take care of the data near the top of the window not being updated. Feel free to re-open if this change doesn't solve all of your problems.
