### ISSUE TITLE
Thumbnails fail to embed on mkv files, but embed on mp4 files

### ISSUE THREAD

**Issue by Gadetron** [axcore/tartube#426]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 10

### What version of Tartube are you using?
2.4

the output log shows the webp thumbnail being converted and appended to the video file, but the video file doesnt show the thumbnail, however if i let it convert to mp4 instead, it does append it correctly

**Comment by Gadetron** [comment]
if i go into vlc player and check the metadata it shows the right thumbnail, but the file explorer does not

**Comment by axcore** [comment]
Download one of the affected videos. Then show me the contents of the **Output** tab, especially including the yt-dlp at the top (in yellow).

**Comment by Gadetron** [comment]
> Download one of the affected videos. Then show me the contents of the **Output** tab, especially including the yt-dlp at the top (in yellow).

![image](https://user-images.githubusercontent.com/66714928/168337085-b29f4fb0-62ab-487c-a6b3-5f3375d37043.png)

![image](https://user-images.githubusercontent.com/66714928/168337099-e231f2cf-6eaf-46af-83c6-636f6e4f9550.png)

**Comment by Gadetron** [comment]
![image](https://user-images.githubusercontent.com/66714928/168340446-ff7a582f-7f20-4f3a-aa5f-83d15fe19b50.png)


![image](https://user-images.githubusercontent.com/66714928/168340456-ff337067-fd88-4db9-9420-10b03838a73d.png)

**Comment by axcore** [comment]
I'm a bit confused here, the thumbnail visible in your File Explorer is the same one visible on YouTube's website. Which thumbnail were you expecting to see?

![monster](https://user-images.githubusercontent.com/37951926/168751484-dbc3b11f-816d-4f6d-bf98-94cbfeb41f4e.png)

On my Linux box, I tested the same command using yt-dlp only (no Tartube), and I see the actual problem you describe:

![monster2](https://user-images.githubusercontent.com/37951926/168752566-8c60a84d-3363-44e1-b1e9-32586c9f20f6.png)

I'm not sure why it doesn't work or how to fix it.

>the video for some reason has to go through a lengthy conversion process to become an mp4, despite the fact that mp4 is part of the supported file types for the video

`yt-dlp --newline -i --hls-prefer-native --cookies cookies.txt --write-thumbnail -f "bestvideo[height<=?1080]+bestaudio/best[height<=?1080]" --recode-video mkv --embed-thumbnail --verbose https://www.youtube.com/watch?v=DMqXaAWuzqM`

Your yt-dlp command includes `--recode-video`, so that's what happens. FFmpeg converts the .webm to .mp4 which will take several minutes. If you want to download the original .mp4 from YouTube, rather than converting it, then you have to actually specify that. For example, in the Classic Mode tab, make sure **Download in this format** is selected:

![monster3](https://user-images.githubusercontent.com/37951926/168753613-5d995942-d79c-4245-8ba1-d8e7ba75ff9f.png)

If you're using the Videos tab, then it's **Edit > General download options > Formats**, set up like this:

![monster4](https://user-images.githubusercontent.com/37951926/168753847-bb8828a4-2cae-4d62-81db-8a4d47e0d3a5.png)

**Comment by Fijxu** [comment]
Same problem here, VLC shows the thumbnail but the explorer not (Dolphin file explorer). I download the videos in VP9 .webm then reencode or remux them to mkv for thumbnail support. But the thumbnails in MKV doesn't show up, but they are in the video metadata.

![image](https://ii.zzls.xyz/QLTEGQI.png)

**Comment by axcore** [comment]
Thumbnails were not embedded because Tartube was converting .webp thumbnails to .jpg (to make them visible in its window), so the .webp files didn't exist when FFmpeg tried to embed them. 

I think this issue is the same one mentioned in #461. Today's release (v2.4.165) should fix both of them, but feel free to open a new issue if the new code doesn't work as expected.

**Comment by axcore** [comment]
Closed for inactivity.
