### ISSUE TITLE
Tartube just deleted a ton of unsorted videos how do I get them back

### ISSUE THREAD

**Issue by beachboys95** [axcore/tartube#427]
I went to clear the videos from my unsorted videos folder and Tartube actually deleted the files. Can I get them back? Please help me.

Did Tartube change the way files are deleted? I swear you used to have to specify to delete it from the hard disk.

**Comment by ceonelson** [comment]
Hmm I do seem to remember there being a dialog prompt as to whether the delete was just from the Tartube db or also from disk, but it seems to delete from disk now. I checked through the Preferences and couldn't find one that referenced that, but I'd definitely prefer the choice on deleting.

Maybe it can be like windows explorer does - pressing delete only removes from tartube db, while shift+delete removes from db and filesystem?

As to your issue now, since they're deleted from the filesystem your options to get them back are to restore from a backup or shadow copy (if on windows) or failing that to restore a prior version of your tartube db from before the delete and tell it to redownload all files in the folder.

If you've done other downloading since the deletion and don't want your main tartube db out of sync, you can create a new tartube db folder (say "recovery") and then put your backup db in there as tartube.db and re-download in that folder.

**Comment by axcore** [comment]
There is a dialogue when you try to delete a channel, playlist or folder, but there isn't a dialogue when you delete one or more videos directly. I understand that this behaviour seems inconsistent, but from another point of view, when you're trying to delete (say) twenty videos from a folder, it gets seriously annoying having to deal with that many dialogue windows.

Regarding backups: Python (and other languages) will delete a file immediately, they don't get sent to the Recycle Bin. The only way to un-delete them would be with a disc recovery tool.

By default, Tartube preserves the previous database save in the .backups folder, but if you've re-started Tartube a few times since you lost your videos, that will be gone.

**Comment by ceonelson** [comment]
> There is a dialogue when you try to delete a channel, playlist or folder, but there isn't a dialogue when you delete one or more videos directly. I understand that this behaviour seems inconsistent, but from another point of view, when you're trying to delete (say) twenty videos from a folder, it gets seriously annoying having to deal with that many dialogue windows.

I think that if someone selected 20 videos from a folder, their intention as to whether they wanted to remove them from the tartube db or delete them from disk would be the same.  What do you think @beachboys95 ?

If there are multiple videos selected and the user goes to delete, I would suggest to show the remove from db/delete from disk prompt, and then just apply that action to all of the selected videos :)

**Comment by axcore** [comment]
>How could I have accessed that, and what would I have been able to do with it?

It's in Tartube's data folder. If you're on LInux it's invisible, press CTRL+H to make it visible. If you're on Windows it won't be invisible. See [here](https://github.com/axcore/tartube#75-videos-are-missing-after-a-crash) for more.

**Comment by ceonelson** [comment]
> Is there any chance I could recover at least the list of what was previously in the folder at this point, or is Recuva my best option here to recover stuff?

That's what I was trying to explain in my original post. 

See this for more explanation:

https://github.com/axcore/tartube#6212-multiple-databases

Then just copy your tartube backup db from your original folder into your new folder and name it tartube.db and it should show your list (assuming the backup db has them).

FYI, I have tartube set to create a backup db after every operation, and just delete most of the backup files every week or so. It's saved me a few times in the past, so I'd recommend doing that (or at least daily backups).

https://github.com/axcore/tartube#75-videos-are-missing-after-a-crash

**Comment by axcore** [comment]
>Would it not have logged what was there previously still?

The default setting is to preserve only the current and previous database save. If you didn't enable one of the options in Edit > System preferences > Files > Backups then there probably isn't a way to retrieve your old database saves.

**Comment by axcore** [comment]
@ceonelson, what do you think about making "Make a new backup file once per day" the default setting instead?

**Comment by ceonelson** [comment]
@axcore I think that would be a good default setting as the db files aren't large and being able to go back a day could be extremely helpful in certain situations.

I do also think though that it would be user friendly to show the same delete action prompt from the channels when a video is deleted, and if there is more than one video selected just have the prompt say "this action will apply to all currently selected videos" so you don't have to show the same prompt each time.

There could be an advanced option to set the default action of remove from db or delete from disk if they want.

I think having the delete button just remove from db and shift+delete delete from disk would be a nice shortcut to skip the prompt for power users who might want to take a different action depending on the context but not have to use the prompt each time :)

**Comment by axcore** [comment]
Ok, I have some time at the weekend, so I will think about the best way to add both of your suggestions.

**Comment by axcore** [comment]
Ok, in v2.4.065 I've made some changes.

Firstly, when installing Tartube, the user is asked to choose how often to backup their database file. The new default option is "every time".

![setup1](https://user-images.githubusercontent.com/37951926/171206635-695e7457-e14d-4e2a-a124-2650fbf0f92a.png)

Secondly, when deleting videos the user will get a confirmation prompt, just as they already do when deleting a channel, playlist or folder.

In all cases, the prompt can be disabled (and later re-enabled in **Edit > System preferences > Files > Delete**).

![setup2](https://user-images.githubusercontent.com/37951926/171207085-11babec0-60c5-49b3-9e8f-21a70031c8ad.png)

I looked into moving files to the Recycle Bin, rather than deleting them directly. The recommended method is the Python [Send2Trash](https://pypi.org/project/Send2Trash/) module, but it doesn't work at all on MS Windows under MSYS2, and it doesn't delete folders/directories on Linux, so that change will have to stay on the backburner for now.
