### ISSUE TITLE
Code location

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#429]
Could you let me know where in the code the "download option" command line is generated?

For example, I have download option 1080p in channel test. Where in the code are those combined to generate the command line that is used to download it?

Thanks Axcore!

**Comment by ceonelson** [comment]
Going through the code more it looks like this is where the output string is generated, either putting in the full path to the file or using the --paths folders specified in download options, is that right?

https://github.com/axcore/tartube/blob/f4d2927cd2fa4fab9a39209889856597fdf9de1e/tartube/options.py#L1716

**Comment by axcore** [comment]
Sorry, I forgot this conversation was in progress. Feel free to ping me continuously if I forget again,

>Going through the code more it looks like this is where the output string is generated, either putting in the full path to the file or using the --paths folders specified in download options, is that right?

Ok, I have been examining the code and discovered that the internal value `save_path_list` doesn't actually do anything; that might be the source of your confusion, because comments throughout `options.py` say that it does do something useful.

(Before v2.3.228 there was an intermediate stage; the current version of `.build_paths()` dispenses with that intermediate stage, and adds `--output` and `--paths` to the system command directly.)

**Comment by axcore** [comment]
The updated code/comments are in v2.4.065.

**Comment by axcore** [comment]
Closed for inactivity
