### ISSUE TITLE
Allow duplicate name

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#439]
In the current version (2.4.077) Tartube doesn't allow duplicate names for playlist which is very annoying issue. May you please allow duplicate naming for playlist.

Example: 
I'm unable to add "Season1" playlist although it's available in different folder.

![image](https://user-images.githubusercontent.com/284547/174100035-f6547a39-7e0a-4332-a596-7ae7fe06b7d4.png)

**Comment by axcore** [comment]
That would be very difficult, because Tartube uses the name to identify the channel/playlist/folder. I would have to rewrite most of the code, and that would take a very long time.

Workaround: right-click the playlist and select **Playlist actions > Set name**. It won't change the name of the folder on your filesystem, but it's better than nothing.

**Comment by axcore** [comment]
Added in v2.4.143. It was a lot of work, so I hope you like it :)

![duplicate](https://user-images.githubusercontent.com/37951926/202757809-08e487db-d0b3-4e51-8f81-171f844c9b8e.png)

You can now create separate channels called **Season 1**, as long as they aren't in the same folder.

**Comment by mbnoimi** [comment]
Thank you very much
