### ISSUE TITLE
Tartube doesn't download from certain websites

### ISSUE THREAD

**Issue by SuperPoorMan** [axcore/tartube#442]
Thanks for taking the time to submit a bug report! Please include the following information:

Windows 10, Tartube V 2.4.077

Here is my shameful link that I cannot download
https://spankbang.com/6xojj/video/kati3kat+mommy+milkers
This happens on most videos from this website lately and I am not entirely sure why. The error message is just "I can't do it" kinda situation.

**Comment by axcore** [comment]
Video websites change their code over time, which means that yt-dlp must be updated. 

yt-dlp is updated frequently for the more popular websites, but for the smaller ones, you will probably have to submit the error report yourself: [yt-dlp issues page](https://github.com/yt-dlp/yt-dlp/issues).

I tested your link with just yt-dlp (not Tartube) and got the same result:

`yt-dlp https://spankbang.com/6xojj/video/kati3kat+mommy+milkers
[SpankBang] 6xojj: Downloading webpage
ERROR: [SpankBang] 6xojj: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
`
