### ISSUE TITLE
Easier update of Portable Edition: Cleaner Separation between config in Settings.json, Database Config & Executable Code (that changes structure & files with each release)

### ISSUE THREAD

**Issue by xbliss** [axcore/tartube#454]
Easier update of Portable Edition: Cleaner Separation between config in Settings.json, Database Config & Executable Code (that changes structure & files with each release)

A. The folder & files tree structure between various versions is quite different (Using Beyond Compare GUI)
- A lot of "extraneous" files are there 
-  Even between the Same version of a "fresh portable" extract compared with one that has been actively used. 

(Something you can check yourself and if need be I can share some screenshots). 

B. Upon asking you elsewhere it was made apparent that only the following files matter to be kept: 

> There is only one config file. To see its location, click Edit > System preferences... > Files > Config.
> 
> If you are worried, make a copy of this file, install Tartube, then move the file back to one of the locations.
> 
> There is only one config file, but there is a separate database file. It is called tartube.db and it is stored in the same folder as your downloaded videos.
> 

Ergo...  

- Config File: Settings.json
- Default Location: /tartube/home/user/tartube/settings.json 
- Non Portable Install: ... windows based paths.. 

- DB File(s): tartube.db
- Default Location: /tartube/..

Given that DBs can be created and separated away from the "Code" Paths, that's good. Have done that for both the Installed Setup and Portable on an external HDD. 

What would be nice is to have 

1. "clear separation" of "Relevant Files" 
2. As mentioned in Point A above, the structures keep changing 
3. And in the lack of an installer, we wonder if Nuking previous portable version, we might lose something. (Which seems likely at some point). 
4. Can we separate the Settings & other "generated" files (outside of Nuke-able folders/ code) that can be "REPLACED" with minimal caution i.e. Nuke older, Extract Drag Drop newer.

**Comment by axcore** [comment]
This is a very short answer, because I am very busy. Please ask for clarification, if you need it.

There is only one important file: the settings.json file. If you are using the portable installer, then it is safe to "nuke" the old installation. You will not lose anything, you just need to install yt-dlp and FFmpeg again.

I know that the installer creates a lot of files. But most of these files are created by [MSYS2](https://www.msys2.org/). I don't control them. I only control the Tartube folder (the folder that contains `setup.py`). The relative location of this folder never changes.
