### ISSUE TITLE
System Locale 'es_CL' not set - can't open System Preferences

### ISSUE THREAD

**Issue by raxdraws** [axcore/tartube#528]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 10 22H2 19045.2728

### What version of Tartube are you using?
Tartube 64-bit v2.4.260

I have a problem with system locale, the problem is with value: 'es_CL' not set (my system locale)
![image](https://user-images.githubusercontent.com/85380755/228088755-2d5833b1-2575-464b-af4f-9fecdf2eeacb.png)
I tried to change the folder name for 'es' to 'es_CL', but that doesn't work.
![image](https://user-images.githubusercontent.com/85380755/228088915-15711672-1c64-464c-b1cd-c99450997690.png)
I tried search options.json (or was settings.json?) to edit, i reinstalled Tartube, FFMPEG, yt-dlp, and Python too, and nothing works, even i deleted the tartube.db files.
I need a solution to this thing, i can't open System Preferences, even "Check DB Integrity" give no errors.
![image](https://user-images.githubusercontent.com/85380755/228089211-f4a1f06d-a462-4f24-aa80-890e6b64d164.png)

**Comment by axcore** [comment]
This looks like a duplicate of https://github.com/axcore/tartube/issues/518, which was fixed in v2.4.277.

If you want, you can update your Windows installation with new source code downloaded from Github, as described [here](https://github.com/axcore/tartube#tartube-won-t-install-won-t-run-doesn-t-work).

But there will be a full release at the end of this month, so maybe you can wait for that.

**Comment by raxdraws** [comment]
The problem was resolved using the most recent updated source code.
Now when access to Settings, appears the option for select the appropriate locale for the program.
