### ISSUE TITLE
Updating Tartube

### ISSUE THREAD

**Issue by harryray33** [axcore/tartube#535]
I'm running Tartube 2.4.255 on Win 7...Is it possible to update through the programme, or do I have to download the new version 2.4.260?

I tried the check for updates, but it just gave me the new version numbers, and I can't see a way to update it.

Thanks

**Comment by axcore** [comment]
The most recent major release is v2.4.260. 

Compiling those releases takes several hours, but I upload minor updates to Github more frequently. If you want to, you can download the new source code from here and copy it into your Windows installation, replacing the old source code, as described [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work).

Generally speaking, it is worth updating the source code in this way if you don't want to wait for the next major release, for example because it fixes a bug you have found, or because you want to test a new feature.
