### ISSUE TITLE
How to download video only instead of entire playlist?

### ISSUE THREAD

**Issue by bheeshmpita** [axcore/tartube#569]
When i use links of videos from playlist, tartube downloads entire playlist instead of that particular video.
Which setting should i modify to fix this?

**Comment by mokun** [comment]
I have the same issue on youtube videos that is a part of a playlist.

Is there a option to change that ?

Can someone take a look ? Appreciate that !

**Comment by axcore** [comment]
Guys, if your problem is "I can't download this playlist", please give me the URL of the playlist. 

Are we talking about YouTube playlists? Sorry, you can't use those URLs to download a single video. You have to remove the **&list=XXX** for every URL. For example

https://www.youtube.com/watch?v=94ehW82PYZQ**&list=PLacCkdZ--84TWBOovLa4QF6d7cjQMkKhg&index=1**

**Comment by bheeshmpita** [comment]
> You need to edit the video's URL, removing the &list=XXXX part
Thanks. If possible, can we have this feature in future versions of tartube where the software does this URL modification part itself?
