### ISSUE TITLE
Need help with preferred format on odysee.com

### ISSUE THREAD

**Issue by JimZiii** [axcore/tartube#575]
Some videos on odysee has the original file in 1080p and then another one in 1080p-144p using a codec, so it's smaller size (I'll add a screenshot showing the formats)

Problem is, i can't seem to find a option for prioritizing the ones with a codec. And the format id's are different on odysee and they're not supported in the app so i can't type it in manually, instead of just numbers they're "hls-" and 3 or 4 numbers (hls-4026) is 1080p.

I've tried the hls 1080 option but it still grabs the original 1080 file.

How can i get tartube to grab the correct file for me? Are there any workarounds i could use to get the result i want?

This is an example video that has both types of files
https://odysee.com/@SunnyV2:7/the-rapper-who-got-a-20-anne-frank-face:1

![Screenshot_20230722_201443_Seal.jpg](https://github.com/axcore/tartube/assets/7854537/8d48795c-8bd0-4c32-afa1-795dfe9050e8)

**Comment by axcore** [comment]
First step is always to check that the video is actually available in the format you want. Looks like you've already done that; for anyone else reading this thread, in Tartube's Videos tab you can right-click a video and select **Fetch > Available formats**. The output will be visible in the Output tab.

In the download options window (Edit > General download options...), you can use the box **Additional download options** to specify an unusual format directly. For example:

`-f hls-4026`

You can tweak this line to specify several preferred formats, if you want; see the [yt-dlp documentation](https://github.com/yt-dlp/yt-dlp#format-selection).

I tested your video and got a 110Mb file, rather than the 180Mb default download, so it appears to be working as expected.
