### ISSUE TITLE
Windows 7 no longer supported

### ISSUE THREAD

**Issue by harryray33** [axcore/tartube#578]
Is Win 7 no longer supported on the latest version? I'm using the portable version.

If it isn't, is there a way round it?

Thanks

**Comment by axcore** [comment]
The [MSYS2 website](https://www.msys2.org/docs/windows_support/) suggests that support for Windows 7 has ended.

You can continue using old Tartube installers. You can update the Tartube code itself quite easily, see [here](https://github.com/axcore/tartube#update-tartube-on-ms-windows). 

You can convert an ordinary installation into a portable installation by creating an empty `settings.json` file in` ..\msys64\home\user\tartube`, and by copying `..\msys64\home\user\tartube\pack\portable\tartube_portable_64bit.bat` into the installation folder (i.e. the folder that contains the msys64 sub-folder).

**Comment by harryray33** [comment]
Thanks, I'm afraid coding is beyond me..it's baffled me.

Is there a way of just copying over some folders from the last release, and overwriting the folders on the newer release? If so, what files and folders are these?
Or, is it possible for you to publish a release with the new tartube that uses the old MSYS2 (whatever that is).

**Comment by axcore** [comment]
Tartube is an application for Linux. In order to get it working on Windows, we have to install a copy of Linux on your Windows computer. That is what [MSYS2](https://www.msys2.org/) is - a very small version of Linux, with everything except the most essential components removed.

Unfortunately, MSYS2 developers don't have the resources to support older versions of Windows. Support for Windows 7.1, and for 32-bit Windows, has already been dropped; eventually support for Windows 8 will be dropped too.

As you say, in theory it should be possible to just use an older version of MSYS2, one that can be run on older versions of Windows. And that would be fine, except for one big problem: most Tartube users need to install FFmpeg, but the old software libraries from which FFmpeg are downloaded are no longer available. 

I only recently started offering Tartube installers with FFmpeg already included. It looks like the first one was [v2.4.165 from November 2022](https://sourceforge.net/projects/tartube/files/v2.4.165/); you can try installing it on your Windows 7 system.

After installing Tartube on Windows, everything should be in one folder. (You choose the folder during the installation process.) Converting that folder into a portable installation is easy, you just need to create one file, and move another file (as described above).

Likewise, update Tartube itself is also easy; you just download the latest source code files, and just use them to replace the old source code files, as described [here](https://github.com/axcore/tartube#update-tartube-on-ms-windows).

Otherwise, your choices are: (1) Update your Windows installation, (2) run Tartube in a real virtual environment using VMWare or Virtualbox or something, or (3) use something else instead of Tartube (there is a list of GUIs [here](https://www.reddit.com/r/youtubedl/wiki/index/))

**Comment by harryray33** [comment]
Thanks, I managed to get it going by keeping the older version, and copying over the new Tartube files. I just hope I remember how I did this on the next release of Tartube :0)

Is there any way that you could do this in future versions, to be included in the release?

**Comment by harryray33** [comment]
I've used version 2.4.386 (which appears to be the last to support Win 7) as a baseline, and updating ffmpeg seems to work OK.

**Comment by harryray33** [comment]
I've used 7zip to extract the files from 2.4.386 as you don't include a portable version with ffmpeg.

Hope all the above nonsense makes sense....

**Comment by axcore** [comment]
>I just hope I remember how I did this on the next release of Tartube :0)

Tartube's codebase is quite mature now, if v2.4.386 is working for you, then I suggest that you keep using it until you find a bug that must be fixed. (There is a changelog [here](https://github.com/axcore/tartube/blob/master/CHANGES), if you want to check on that.)

**Comment by axcore** [comment]
The README was updated in v2.4.429.
