### ISSUE TITLE
[Feature Request] Store Media seperate / change folder paths

### ISSUE THREAD

**Issue by Byolock** [axcore/tartube#61]
I've got a Problem with using tartube on a rclone mounted remote filesystem. 
It works fine for the downloads itself but saving the database is not working. 
As this remote filesystem is not that reliable it would be perfect to have the option to store the media seperate from the database. One way i could achive this is creating a new folder (in which I add all channels and playlists) and set its path to the mounted volume. But it seems like tartube does not have that option.

Could you please add such function? Or can you think of any possible workaround?

**Comment by axcore** [comment]
The data directory/folder (containing the main tartube.db file, its backups, temporary files, and all downloaded videos) must be a single directory.

In principle, "instead of downloading videos here, download them here..." would be easy to implement. But in practice, twenty different things can go wrong, and Tartube needs to deal with all of those possibilities. I would have to completely rewrite the code from scratch to make it work.

Also, splitting up the files breaks portability. All the data is stored in one directory, so you can copy the whole directory anywhere, and it magically works anywhere. That is not possible if the files are split up.

I can add a new backup function, if that will help ("if you can't save the database file, save a backup copy on this drive instead..."). But I think the only realistic solution is to find out why your rclone filestyem can't save files.

**Comment by Byolock** [comment]
I understand this is way to much work for such rare use case. The interessting thing is, it works fine the first time (the initial dialog) and creates the database und folders. If I add anything to it and close tartube it seems to not save anything. If i click save database manually i get the error that saving is not possible. The .lock file ist also written and deleted fine. So it has to do something with the way the file is written. As its a database, Tartube will seek in that file right? Probably it is seeking that leads to errors. I will try different caching options and see if this helps or seek help in the rclone forums.

Thanks for your quick answer.

**Comment by axcore** [comment]
Byolock, try this:

1. Find the ../tartube/mainapp.py file, and open it in a text editor
2. Find lines 77-81:

`# Debugging flag (calls utils.debug_time at the start of every function)
DEBUG_FUNC_FLAG = False
# ...(but don't call utils.debug_time from the timer functions such as
#   self.script_slow_timer_callback() )
DEBUG_NO_TIMER_FUNC_FLAG = False`

Change the values to True:

`# Debugging flag (calls utils.debug_time at the start of every function)
DEBUG_FUNC_FLAG = True
# ...(but don't call utils.debug_time from the timer functions such as
#   self.script_slow_timer_callback() )
DEBUG_NO_TIMER_FUNC_FLAG = True`

3. Run Tartube from a terminal window
4. In the Tartube menu, click File > Save database
5. If the database file is saved, you will see this:

`2020-03-03 13:04:11 app 12350 on_menu_save_db
2020-03-03 13:04:11 app 3839 save_db
`

If not, you will see something different, so tell me what you see.

**Comment by Byolock** [comment]
I Managed to work around this issue by using symbolic links for the downloads folder but then yt-dl got problems merging the files. 
I think at this point trying any further to get around the flaws of the filesystem to get it to work is wasting time.
Thanks for trying to debug the issue but the windows implementation of rclone fuse filesystem is just to flawed I guess. I switched to StableBit CloudDrive and had no problems so far.
