### ISSUE TITLE
No video URL provided error even when video is provided

### ISSUE THREAD

**Issue by CFMCGEE** [axcore/tartube#652]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 11

### What version of Tartube are you using?
v2.5.040

### If your bug report is "I can't download this video", please provide a link to the video
I put in any video URL (such as https://www.youtube.com/watch?v=pZXSIKeAWQM) and it I get the error:

![image](https://github.com/user-attachments/assets/ded162e6-2266-41b9-9c69-21932520afef)

It's somehow saying that I didn't provide the URL even if I did. It's been happening since Friday after I downloaded some other videos and then this started happening for no reason.

**Comment by axcore** [comment]
>I put in any video URL

Put the URL where, exactly?

Can you show me the yellow text at the top of the Output tab?

**Comment by CFMCGEE** [comment]
@axcore 

I press on the camera button on the far left and press "ok" and then press the "Download all" and it gives me the error previously messaged. 

![image](https://github.com/user-attachments/assets/2f302b30-4224-42e9-9ba7-827bb2d78bb8)

![image](https://github.com/user-attachments/assets/c4ace707-d873-4e95-b3ab-d12e87c51d4b)

**Comment by axcore** [comment]
I tried the same thing, and everything behaved as expected:

1. Click the camera icon
2. In the popup window, enter https://www.youtube.com/watch?v=pZXSIKeAWQM
3. Click OK to close the popup window
4. Click **Download all** in the bottom left corner

![windowstest](https://github.com/user-attachments/assets/314d6cfb-aa11-4182-8bed-c711ccbe6e4c)

I can't explain your results, but you could try these things...

1. Instead of using the **Download all** button, right-click the video and select **Download video**
2. Try clicking **Edit > General download options**, and in the new window, click **Completely reset all download options to their default values**

**Comment by CFMCGEE** [comment]
@axcore 

It worked after I did the second of your suggestions with resetting the download options to their default values. 

I'm not sure why it even happened to be honest. Thanks for the help.
