### ISSUE TITLE
WARNING: Skipping yt-dlp as it is not installed.

### ISSUE THREAD

**Issue by Tanrirem** [axcore/tartube#666]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
windows 11

### What version of Tartube are you using?
v2.5.059

When I check a channel, it shows "nothing happened" page, from there I do update yt-dlp and it shows this
![image](https://github.com/user-attachments/assets/4f35543f-a1f8-4975-b526-2d25b73ed88f)

Sorry this will go beyond bug report but I really need help:

I also have no idea how to import cookies, the thing in the FAQ leads to something about yt-dlp which I cannot find a console within tartube, so I have no idea how to use the link provided to import cookies, also I think when I tried to sign into youtube within tartube it said you don't have to do that or it doesn't work or something. Can you please help me set this up? I a few days ago barely made it work and I had to spend an entire day to make it work, and it broke again now and it's really annoying.

All I want to do is automatically scrape a channel's livestreams, they unlist their livestreams sometimes (so I want to download right when they finish). https://www.youtube.com/@58mw91 <-- this is the channel. Thank you for creating awesome tool, it's perfect for what I want to do but I cannot get it to work properly..

**Comment by Rygle** [comment]
Same here. Latest version, yt-dlp seems to have been skipped in the build.

Windows version "install-tartube-with-ffmpeg-2.5.059-64bit.exe"

**Comment by Rygle** [comment]
OK, here's my temporary work-around until this issue is resolved. This is for Windows.

Because I installed the new version, the tartube.db database was upgraded, as was the settings.json file, so when I went back to the previous version, it was very unhappy.

I re-installed the new version (2.5.059), which could open the tartube.db database. I then went to Media->Export and exported the database and all media in it as a json file.

I then closed Tartube 2.5.059 and re-installed 2.5.040.

I found my tartube.db and renamed that. It has a version number in it that I could see in a text editor, but it's not an SQL Lite format but some other python format, so I didn't dare edit it in case it corrupted the file. That is why I exported the media library as a json file (see above).

When I went to open 2.5.040, it was unhappy because of the settings file.

I searched and found settings.json in C:\Users\{username}\AppData\Local\Tartube\msys64\home\user\tartube (or wherever you put it)

I edited the settings.json file with a text editor and just changed the version number in the second line from "script_version": "2.5.059" to "script_version": "2.5.040" and saved the file.

I then re-installed Tartube 2.5.040, and it accepted the settings file with the minor edit.

I then went to Media->Import and imported the json file I exported before.

After that, 2.5.040 seems to work again.

**Comment by Rygle** [comment]
Seems to work great! After installing, had to update yt-dlp before it would work and it said the update failed (there were messages about pipx and a virtual python environment), though the log said it installed in the end despite the final dialogue message that it failed. Also tried updated FFMpeg and it also gave an error but seemed to actually install despite a dialogue saying it failed - I think that was mainly because all the same versions of files were already present.

**Comment by axcore** [comment]
Yes, the "errors" are actually non-fatal warnings, yt-dlp is actually installed all the same.

**Comment by Rygle** [comment]
Thank you for fixing this issue and for a great app!
