### ISSUE TITLE
Track Downloaded Videos By Channel

### ISSUE THREAD

**Issue by bind4** [axcore/tartube#674]
I have a laptop so storage is an issue (not using an external drive). Trying to find a way to track downloaded videos by YT channel, then be able to move the files to cloud storage, but keep the moved videos' status appear as downloaded still in Tartube. This way even if the files are no longer there I know which has been downloaded. Tried using Tidy channel action to 'delete videos but not remove from db' but hoping to keep that status of downloaded which is helpful when filtering videos in the checked videos list above. The 'archived' status is already taken but that's kind of the idea.

Edit: just realized I didn't ask a question but is there a way to accomplish the above in Tartube?

TIA

**Comment by axcore** [comment]
As I understood your question, you want to know what you need to do after moving videos to another device (or to the cloud). The answer is nothing; Tartube has a database of videos so it doesn't mind if the actual files no longer exist in the original download folder.

If you also move the _thumbnails_ to another device, then of course you won't be able to see them in Tartube's window.

Tartube does not mind missing videos, but yt-dlp does. You should use archive files so that yt-dlp doesn't try to download a video more than once, [as described here](https://github.com/axcore/tartube?tab=readme-ov-file#79-download-all-button-takes-too-long). When you move  the videos to the cloud, be careful not to move the archive files as well.

**Comment by bind4** [comment]
Thank you! I will give this a try.

**Comment by bind4** [comment]
@axcore I think I moved the thumbnail files when trying to move files previously. I tried moving everything but the archive file. Thanks for your time!
