### ISSUE TITLE
Do I really have to reinstall youtube-dl and ffmpeg just for tartube?

### ISSUE THREAD

**Issue by KirbyFan102** [axcore/tartube#82]
I have youtube-dl and ffmpeg installed in my PATH already. Is there anyway to make tartube use those, instead of me having to install them twice just so tartube can work?
Also, where are the video download folders for tartube located on Windows? I really wish I could find them so I could add or move videos without tartube's clunky interface.

**Comment by axcore** [comment]
Tartube is a Linux application that uses Linux graphic libraries. The installer for MS Windows contains a [miniature Linux](https://www.msys2.org/) so that everything works. You have to install separate copies of youtube-dl and ffmpeg because you're installing the Linux versions.

I realise this is inconvenient, which is why you can install/update both of them from Tartube's main menu. It's literally a two-click operation.

Of course, an extremely clever Windows developer might be able to figure out a way to get native youtube-dl and ffmpeg working with Tartube. But I'm not a Windows developer at all.

The video download folders are located wherever you chose to locate them, the first time you ran Tartube. Click **File > Database preferences**... and see the box marked **Tartube data directory**.

Regarding the clunky interface, [see this](https://github.com/axcore/tartube/issues/77#issuecomment-617889565).

**Comment by KirbyFan102** [comment]
Well, that's good to know. I suppose I'll have to wait for the next release, then.

**Comment by KirbyFan102** [comment]
Is there a way to make tartube just download videos to a specific location, instead of creating all these unnecessary folders?

**Comment by axcore** [comment]
Edit > General download options ... > Files > Filesystem 
Select Download all videos into this folder, then select the folder

**Comment by KirbyFan102** [comment]
Excellent. Finally, someone understands! Thanks for the info.
